name: Build experimental build
permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
  push:

jobs:
  build_xm_experimental:
    runs-on: windows-latest
    strategy:
      matrix:
        targetplatform: [x64]
        ChannelName: [Release]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore "source/XeniaManager.Desktop/XeniaManager.Desktop.csproj"

      - name: Test
        run: dotnet test "source/XeniaManager.Desktop/XeniaManager.Desktop.csproj"

      - name: Get experimental build version
        id: get_version_info
        shell: pwsh
        run: |
          $currentDate = (Get-Date -Format "yyyy-MM-dd")
          $sha = git log -1 --pretty=%H
          $shortSha = $sha.Substring(0, 7)
          $versionTag = "$currentDate-$shortSha"

          echo "COMMIT_SHA_SHORT=$shortSha" >> $env:GITHUB_ENV
          echo "VERSION_TAG=$versionTag" >> $env:GITHUB_ENV

      - name: Publish the app
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:EnableCompressionInSingleFile=true -p:DebugType=none -p:PublishReadyToRun=false -p:InformationalVersion="${{ env.VERSION_TAG }}" -p:DefineConstants="EXPERIMENTAL_BUILD" -o publish/desktop "source/XeniaManager.Desktop/XeniaManager.Desktop.csproj"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xenia_manager
          path: ./publish/desktop/XeniaManager.exe

      - name: Package
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop'))
        run: |
          Compress-Archive -Path .\publish\desktop\* -DestinationPath .\xenia_manager.zip

      - name: Get latest release from experimental-builds repo
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop'))
        id: get_latest_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/xenia-manager/experimental-builds/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        continue-on-error: true

      - name: Generate changelog
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop'))
        id: generate_changelog
        shell: pwsh
        continue-on-error: true
        run: |
          $lastCommitSha = ""
          if ("${{ steps.get_latest_release.outputs.status }}" -eq "200") {
              $jsonData = @'
          ${{ steps.get_latest_release.outputs.data }}
          '@
              $releaseData = $jsonData | ConvertFrom-Json
              $latestReleaseTag = $releaseData.tag_name
              if ($latestReleaseTag -match '(\d{4}-\d{2}-\d{2})-([a-f0-9]{7})') {
                  $lastCommitSha = $matches[2]
              }
          }
          ./scripts/generate_changelog.ps1 -LastCommitSha $lastCommitSha

      - name: Check if release exists
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop'))
        id: check_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/xenia-manager/experimental-builds/releases/tags/${{ env.VERSION_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        continue-on-error: true

      - name: Update commit SHA in experimental-builds repo
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop'))
        shell: pwsh
        run: |
          git clone https://github.com/xenia-manager/experimental-builds.git temp-repo
          cd temp-repo
          git config user.email "214508751+xeniamanager-ci@users.noreply.github.com"
          git config user.name "xeniamanager-ci"
          echo "${{ env.COMMIT_SHA_SHORT }}" > latest_build_commit.txt
          git add latest_build_commit.txt
          if (git diff --staged --quiet) {
              echo "No changes to commit"
          } else {
              git commit -m "Update latest build commit SHA: ${{ env.COMMIT_SHA_SHORT }}"
              git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/xenia-manager/experimental-builds.git main
          }

      - name: Create new release
        if: github.event_name == 'workflow_dispatch' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/develop')) && steps.check_release.outputs.status != '200'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xenia-manager/experimental-builds
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.VERSION_TAG }}
          body: ${{ env.CHANGELOG }}
          make_latest: true
          files: ./xenia_manager.zip